---
#- name: Create Wordpress project directory on host
#  file: 
#    path: "{{ project_folder }}/wordpress"
#    state: directory
#    owner: root
#    group: root
#    mode: 0700

- name: Copy Wordpress Dockerfile file to host
  template:
    mode: 0700
    src: wordpress.Dockerfile.j2
    dest: "{{ project_folder }}/wordpress/Dockerfile"

- name: Copy dynamic preconfiguration files for Wordpress
  template:
    mode: 0700
    src: default-ssl.conf.j2
    dest: "{{ project_folder }}/wordpress/default-ssl.conf"

- name: Copy static preconfiguration files for Wordpress
  copy:
    mode: 0744
    src: .
    dest: "{{ project_folder }}/wordpress/" 

- name: Launch Wordpress service through docker-compose
  docker_compose:
    build: yes
    project_src: "{{ project_folder }}" 
    services:
      - wordpress
  tags: [ 'wordpress' ]