---
- name: Create project directories on host
  file: 
    path: "{{ project_folder }}/{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0700
  loop: 
    - wordpress
    - mariadb
    - phpmyadmin

- name: Copy Dockerfiles and docker-compose file to host
  template:
    mode: 0700
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: wordpress.Dockerfile.j2, dest: "{{ project_folder }}/wordpress/Dockerfile" }
    - { src: mariadb.Dockerfile.j2, dest: "{{ project_folder }}/mariadb/Dockerfile" }
    - { src: phpmyadmin.Dockerfile.j2, dest: "{{ project_folder }}/phpmyadmin/Dockerfile" }
    - { src: docker-compose.yml.j2, dest: "{{project_folder}}/docker-compose.yml" }

- name: Copy preconfiguration files for Wordpress
  copy:
    mode: 0700
    src: "{{ item.src }}"
    dest: "{{ item.dest }}" 
  with_items:
#    - { src: html, dest: "{{ project_folder }}/wordpress/"}
    - { src: phpmyadmin, dest: "{{ project_folder }}/phpmyadmin/" }
    - { src: mysql, dest: "{{ project_folder }}/mariadb/"}

#- name: Launch Docker services through docker-compose
#  docker_compose:
#    build: yes
#    project_src: "{{ project_folder }}" 
#    tags: fullwp

- name: Launch db service through docker-compose
  docker_compose:
    build: yes
    project_src: "{{ project_folder }}" 
    services:
      - db
  tags: [ 'db' ]
    #when: "'db' in ansible_run_tags"

- name: Launch wordpress service through docker-compose
  docker_compose:
    build: yes
    project_src: "{{ project_folder }}" 
    services:
      - wordpress
  tags: [ 'wordpress' ]
    #when: "'wordpress' in ansible_run_tags"
    
- name: Launch pma service through docker-compose
  docker_compose:
    build: yes
    project_src: "{{ project_folder }}" 
    services:
      - phpmyadmin
  tags: [ 'phpmyadmin' ]
    #when: "'pma' in ansible_run_tags"
