---
- name: Set server timezone
  timezone:
    name: "{{ desired_timezone }}"

- name: apt update and upgrade 
  apt:
    upgrade: yes
    update_cache: yes

- name: Install UFW (for uncomplicated fire - wall)
  apt:
    name: ufw
    state: present

- name: Allow SSH traffic 
  ufw:
    rule: allow
    name: OpenSSH

- name: Allow HTTP and HTTPS traffic to docker services ports 
  ufw:
    rule: allow
    proto: tcp
    to_port: 80,443,8080

- name: Add default DENY policy to firewall config
  ufw:
    state: enabled
    policy: deny
    direction: incoming

- name: Update SSH configuration to be more secure.
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
    validate: 'sshd -T -f %s'
    mode: 0644
  with_items:
    - regexp: "^PasswordAuthentication"
      line: "PasswordAuthentication no"
    - regexp: "^PubkeyAuthentication"
      line: "PubkeyAuthentication yes"
    - regexp: "^PermitRootLogin"
      line: "PermitRootLogin no"
    - regexp: "^PermitEmptyPasswords"
      line: "PermitEmptyPasswords no"
  notify: restart ssh 