---
- name: Copy MariaDB Dockerfile file to host
  template:
    mode: 0700
    src: mariadb.Dockerfile.j2
    dest: "{{ project_folder }}/mariadb/Dockerfile"

- name: Copy MariaDB backup file to host
  template:
    mode: 0744
    src: wordpressdb.sql.j2
    dest: "{{ project_folder }}/mariadb/wordpressdb.sql"

- name: Launch MariaDB service through docker-compose
  docker_compose:
    build: yes
    project_src: "{{ project_folder }}" 
    services:
      - mariadb
  tags: [ 'mariadb' ]