---
- name: Verify that Docker is not already installed
  package:
    name:
    - docker
    - docker-engine
    - docker.io
    state: absent

- name: Make sure Docker installation dependencies are installed
  apt:
    name:
    - ca-certificates
    - curl
    - gnupg
    - lsb-release
    state: present

- name: Add Docker official GPG key to apt keyring
  apt_key:
    url: "{{ docker_gpg_key_URL }}"

- name: Add Docker official apt repository to apt sources
  apt_repository:
    repo: "{{ docker_apt_repo }}"

- name: Install Docker through apt
  apt:
    name: docker-ce


- name: Install pip3 to be able to install Docker python dependency/package
  apt:
    name: 'python3-pip'
    state: latest
    update-cache: yes


- name: Install Docker python dependency/package 
  pip:
    name: docker

- name: Install Docker-Compose
  apt:
    name: docker-compose
