---
- name: Copy Certbot Dockerfile file to host
  template:
    mode: 0700
    src: certbot.Dockerfile.j2
    dest: "{{ project_folder }}/certbot/Dockerfile"

- name: Launch Cerbot service through docker-compose
  docker_compose:
    build: yes
    project_src: "{{ project_folder }}" 
    services:
      - certbot
  tags: [ 'certbot' ]

- name: Create cron job to try to renew HTTPS certificate daily
  cron:
    name: "Try to renew HTTPS certificate"
    special_time: daily
    job: "docker-compose -f $(find / -wholename */{{ project_folder }}/docker-compose.yml 2>/dev/null) run --rm certbot renew"