---
- name: Install sudo
  apt: 
    name: sudo

- name: Create stins user with passwort thanks to "mkpasswd -m sha-512"
  user:
    name: stins
    shell: /bin/bash
    uid: 1001
    group: users
    groups: sudo
    append: true # --> user is not removed from any other group
    password: $6$cc9Vs3y3DlIf0Mof$tQyg5Tv79YQLWpLEEpeY0NaK6pCz8E4Dy9U6go4Sh6O4SAi5vcOJNPBU.9sMTNbcIf7qidMg9iskTzUG3E/Jo1

- name: Create stins's .ssh directory
  file:
    path: /stins/.ssh
    state: directory
    owner: stins
    group: users
    mode: 0700

- name: Copy stins's authorized keys
  copy:
    src: authorized_keys_stins
    dest: /stins/.ssh/authorized_keys
    owner: stins
    group: users
    mode: 0600

