---
- name: Install sudo
  apt: 
    name: sudo

- name: Create stins user with passwort thanks to vault and password_hash functionality 
  user:
    name: stins
    shell: /bin/bash
    uid: 1001
    group: users
    groups: sudo
    append: true # --> user is not removed from any other group
    password: "{{ vault_user_pass  | password_hash('sha512') }}"

- name: Create stins's .ssh directory
  file:
    path: /stins/.ssh
    state: directory
    owner: stins
    group: users
    mode: 0700

- name: Copy stins's authorized keys
  copy:
    src: authorized_keys_stins
    dest: /stins/.ssh/authorized_keys
    owner: stins
    group: users
    mode: 0600

