---
- name: Install sudo
  apt: 
    name: sudo

- name: Create sudo user with password thanks to vault and password_hash functionality 
  user:
    name: "{{ user_name }}"
    shell: /bin/bash
    groups: sudo
    append: true # --> user is not removed from any other group
    password: "{{ vault_user_pass  | password_hash('sha512') }}"

- name: Create user's .ssh directory
  file:
    path: "/home/{{ user_name }}/.ssh"
    state: directory
    owner: "{{ user_name }}"
    mode: 0700

- name: Copy user's authorized keys to be the same as the root user
  copy:
    src: /root/.ssh/authorized_keys
    dest: "/home/{{ user_name }}/.ssh/authorized_keys"
    owner: "{{ user_name }}"
    remote_src: yes
    mode: 0600
